#banco de diccionarios para los ENUM que existen en C++
LINES = {'NOLINE':0, 'SINGLELINE':1, 'DOUBLELINE':2}
MODES = {'INT_FLOAT':0, 'INT_INT_INT':1}
PARAMETERS = {'ELEMENT_LENGHT':0, 'THERMAL_CONDUCTIVITY':1, 'HEAT_SOURCE':2}
SIZES = {'NODES':0, 'ELEMENTS':1, 'DIRICHLET':2, 'NEUMANN':3}